In [1]:
import numpy as np

In [27]:
v = np.random.randn(3,3)
print(v)

[[ 0.73176243 -1.37713981 -0.94495971]
 [-1.30719906 -1.65339314 -0.47720081]
 [ 0.96717259  0.6516266   0.03847065]]


In [28]:
e = np.zeros((3,3))
for i in range(0,3):
    projection = 0
    for j in range(0,i):
        projection = projection + v[:,i].dot(e[:,j])*e[:,j]
    e[:,i] = v[:,i] - projection
    e[:,i] = e[:,i]/np.sqrt(np.sum(e[:,i]**2,0))
e

array([[ 0.41037339, -0.88784574,  0.20814329],
       [-0.73307905, -0.45694344, -0.50378349],
       [ 0.54239173,  0.05415385, -0.83837854]])

In [29]:
e[:,2].dot(e[:,2])

1.0